source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AdFooter_Example', :exclusive => true do
  pod "AdFooter", :path => "../"
end

target 'AdFooter_Tests', :exclusive => true do
  pod "AdFooter", :path => "../"

  
end
